DROP TABLE IF EXISTS admin;

CREATE TABLE admin (
    id_admin CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    nama_admin VARCHAR(100) NOT NULL,
    username_admin VARCHAR(100) UNIQUE NOT NULL,
    password_admin VARCHAR(255) NOT NULL,
    email_admin VARCHAR(255) UNIQUE NOT NULL,
    id_gudang CHAR(36),
    deleted_at TIMESTAMP NULL DEFAULT NULL,

    FOREIGN KEY (id_gudang)
        REFERENCES gudang(id_gudang)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

ALTER TABLE `admin` 
ADD COLUMN IF NOT EXISTS `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;